### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by rifat-hossain** [rahulhaque/bKash-payment-gateway-web-demo#1]
There is a throwback on page load.

`Access to XMLHttpRequest at 'https://checkout.sandbox.bka.sh/v1.2.0-beta/checkout/token/grant' from origin 'http://example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by rahulhaque** [comment]
Did you run Chrome in CORS disabled mode? Go through this section [here](https://github.com/rahulhaque/bKash-payment-gateway-web-demo#sandbox-implementation). The APIs are designed to be called from backend. Any web browser will throw CORS exception.
