### ISSUE TITLE
Where can I get the app info?

### ISSUE THREAD

**Issue by shamim0902** [rahulhaque/bKash-payment-gateway-web-demo#7]
![image](https://user-images.githubusercontent.com/43160844/137257068-c5709184-b27a-4fd7-a809-a83edeac0cf3.png)

**Comment by rahulhaque** [comment]
@hasanuzzamanbe You will have to contact bKash and come to an agreement with them. Only they can provide you with these info.

**Comment by shamim0902** [comment]
Thanks for the quick reply, I'm wondering about the test API credentials, I thought a developer can create a test app for them 😐

**Comment by rahulhaque** [comment]
@hasanuzzamanbe unfortunately no. It's all written in the repo. They have a strict policy on this matter. Even sandbox credentials are not open.

**Comment by Prottoy2938** [comment]
@rahulhaque do we have to have/apply for bKash merchant account for this? Or is it possible to do it with the personal bKash account?

**Comment by rahulhaque** [comment]
@Prottoy2938 you'll have to apply for merchant account.
