### ISSUE TITLE
Getting CORS error

### ISSUE THREAD

**Issue by foyzulabrarchy** [rahulhaque/bKash-payment-gateway-web-demo#8]
While using it in front end getting CORS error, in backend works fine. But is there any chance to use it in front end?

**Comment by rahulhaque** [comment]
@foyzulabrarchy according to bKash rules, you must call the API from backend. So, no chance to use it from frontend.

Edit: For development and test purposes, you can disable CORS in Chrome and call the APIs. See [here](https://github.com/rahulhaque/bKash-payment-gateway-web-demo#sandbox-implementation).
